name: face_features
description: Face feature detection app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.7.2+1
  bloc: ^6.1.3
  flutter_bloc: ^6.1.3
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.1.0

flutter:
  uses-material-design: true
